# setwd("path/to/this/dir")
source("../gap.r")
require("plot3D")
set.seed(2)

sims = rbind(sapply(1:2, function(f) rnorm(25)), sapply(1:2, function(f) rnorm(25, mean = if(f==1) 0 else 5)), sapply(1:2, function(f) rnorm(50, mean = if(f==1) 5 else -3)))
ctrs = sapply(1:3, function(f) rnorm(4, sd = 5))
while(min(dist(ctrs)) <= 1) ctrs = sapply(1:3, function(f) rnorm(4, sd = 5))
n50 = runif(4) >= 0.5
plot(sims)
readline()
plot(ref.dist(sims, pc=F))
readline()
plot(ref.dist(sims))
nbap = gap.stat(sims, B=1, pc=F)
print(nbap)
readline()
plot(nbap$Tabs[,1], ylim = c(min(c(nbap$Tabs[,1], nbap$Tabs[,2])), max(c(nbap$Tabs[,1], c(nbap$Tabs[,2])))), xlab = "number of clusters k", ylab = "obs and exp log(Wk)")
lines(nbap$Tabs[,1])
points(nbap$Tabs[,2], pch = "E")
lines(nbap$Tabs[,2])
readline()
plot(nbap$Tabs[,4], ylim = c(min(nbap$Tabs[,4]), max(nbap$Tabs[,4])), xlab = "number of clusters k", ylab = "Gap")
lines(nbap$Tabs[,4])
segments(1:10, nbap$Tabs[,4] - nbap$Tabs[,3], 1:10, nbap$Tabs[,4] + nbap$Tabs[,3])
segments(1:10 - 0.1, nbap$Tabs[,4] - nbap$Tabs[,3], 1:10 + 0.1, nbap$Tabs[,4] - nbap$Tabs[,3])
segments(1:10 - 0.1, nbap$Tabs[,4] + nbap$Tabs[,3], 1:10 + 0.1, nbap$Tabs[,4] + nbap$Tabs[,3])
readline()

sims = rbind(sapply(1:3, function(f) rnorm(if(n50[1]) 50 else 25, mean = ctrs[1, f])), sapply(1:3, function(f) rnorm(if(n50[2]) 50 else 25, mean = ctrs[2, f])), sapply(1:3, function(f) rnorm(if(n50[3]) 50 else 25, mean = ctrs[3, f])), sapply(1:3, function(f) rnorm(if(n50[4]) 50 else 25, mean = ctrs[4, f])))
points3D(sims[,1], sims[,2], sims[,3])
rd = ref.dist(sims, pc=F)
readline()
points3D(rd[,1], rd[,2], rd[,3])
rd = ref.dist(sims)
readline()
points3D(rd[,1], rd[,2], rd[,3])
nbap = gap.stat(sims, B=1, pc=F)
print(nbap)
readline()
plot(nbap$Tabs[,1], ylim = c(min(c(nbap$Tabs[,1], nbap$Tabs[,2])), max(c(nbap$Tabs[,1], c(nbap$Tabs[,2])))), xlab = "number of clusters k", ylab = "obs and exp log(Wk)")
lines(nbap$Tabs[,1])
points(nbap$Tabs[,2], pch = "E")
lines(nbap$Tabs[,2])
readline()
plot(nbap$Tabs[,4], ylim = c(min(nbap$Tabs[,4]), max(nbap$Tabs[,4])), xlab = "number of clusters k", ylab = "Gap")
lines(nbap$Tabs[,4])
segments(1:10, nbap$Tabs[,4] - nbap$Tabs[,3], 1:10, nbap$Tabs[,4] + nbap$Tabs[,3])
segments(1:10 - 0.1, nbap$Tabs[,4] - nbap$Tabs[,3], 1:10 + 0.1, nbap$Tabs[,4] - nbap$Tabs[,3])
segments(1:10 - 0.1, nbap$Tabs[,4] + nbap$Tabs[,3], 1:10 + 0.1, nbap$Tabs[,4] + nbap$Tabs[,3])
readline()

sims = rbind(cbind(seq(-0.5, 0.5, length.out = 100) + rnorm(100, sd = 0.1), seq(-0.5, 0.5, length.out = 100) + rnorm(100, sd = 0.1), seq(-0.5, 0.5, length.out = 100) + rnorm(100, sd = 0.1)), cbind(seq(-0.5, 0.5, length.out = 100) + rnorm(100, sd = 0.1) + 10, seq(-0.5, 0.5, length.out = 100) + rnorm(100, sd = 0.1) + 10, seq(-0.5, 0.5, length.out = 100) + rnorm(100, sd = 0.1) + 10))
points3D(sims[,1], sims[,2], sims[,3])
rd = ref.dist(sims, pc=F)
readline()
points3D(rd[,1], rd[,2], rd[,3])
rd = ref.dist(sims)
readline()
points3D(rd[,1], rd[,2], rd[,3])
nbap = gap.stat(sims, B=1)
print(nbap)
readline()
plot(nbap$Tabs[,1], ylim = c(min(c(nbap$Tabs[,1], nbap$Tabs[,2])), max(c(nbap$Tabs[,1], c(nbap$Tabs[,2])))), xlab = "number of clusters k", ylab = "obs and exp log(Wk)")
lines(nbap$Tabs[,1])
points(nbap$Tabs[,2], pch = "E")
lines(nbap$Tabs[,2])
readline()
plot(nbap$Tabs[,4], ylim = c(min(nbap$Tabs[,4]), max(nbap$Tabs[,4])), xlab = "number of clusters k", ylab = "Gap")
lines(nbap$Tabs[,4])
segments(1:10, nbap$Tabs[,4] - nbap$Tabs[,3], 1:10, nbap$Tabs[,4] + nbap$Tabs[,3])
segments(1:10 - 0.1, nbap$Tabs[,4] - nbap$Tabs[,3], 1:10 + 0.1, nbap$Tabs[,4] - nbap$Tabs[,3])
segments(1:10 - 0.1, nbap$Tabs[,4] + nbap$Tabs[,3], 1:10 + 0.1, nbap$Tabs[,4] + nbap$Tabs[,3])
